# Generated by Django 5.2.8 on 2025-12-07 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('lost', 'Lost Item'), ('found', 'Found Item')], max_length=20)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('books', 'Books & Notes'), ('id_cards', 'ID Cards'), ('keys', 'Keys'), ('clothing', 'Clothing'), ('bags', 'Bags & Wallets'), ('accessories', 'Accessories'), ('other', 'Other')], max_length=50)),
                ('location_lost', models.CharField(blank=True, max_length=200)),
                ('location_found', models.CharField(blank=True, max_length=200)),
                ('date_lost', models.DateField(blank=True, null=True)),
                ('date_found', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lostfound/')),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('returned', 'Returned')], default='lost', max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
