# Generated by Django 4.2 on 2026-01-01 11:51

import cloudinary.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('books', 'Books & Notes'), ('keys', 'Keys'), ('wallet', 'Wallet/Purse'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('other', 'Other')], default='other', max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('contact_info', models.TextField(help_text='Your contact information (phone, email, etc.)')),
                ('date_lost', models.DateField(help_text='Date when the item was lost or found', validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2026, 1, 1)), django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 1, 1))])),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('returned', 'Returned')], default='lost', max_length=20)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image of the item', max_length=255, null=True, verbose_name='lost_found_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lost & Found Item',
                'verbose_name_plural': 'Lost & Found Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
