# Generated by Django 5.2.8 on 2025-12-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='item_type',
            field=models.CharField(choices=[('lost', 'Lost Item'), ('found', 'Found Item'), ('returned', 'Returned Item')], default='lost', max_length=20),
        ),
    ]
