# Generated by Django 4.2 on 2025-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostfounditem',
            name='is_resolved',
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='date_lost',
            field=models.DateField(),
        ),
    ]
