# Generated by Django 5.2.8 on 2025-12-09 08:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0002_alter_lostitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
