# Generated by Django 4.2 on 2026-03-02 10:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0003_alter_lostfounditem_date_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostfounditem',
            name='date_lost',
            field=models.DateField(help_text='Date when the item was lost or found', validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2026, 3, 2)), django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 3, 2))]),
        ),
    ]
