# Generated by Django 5.2.8 on 2025-12-09 08:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='campus_marketplace/profile_pics/default_user.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
