# Generated by Django 4.2 on 2026-01-06 16:27

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('fast_food', 'Fast Food'), ('food_truck', 'Food Truck'), ('bakery', 'Bakery'), ('food_stall', 'Food Stall'), ('other', 'Other')], default='restaurant', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cuisine_type', models.CharField(choices=[('local', 'Local/Kenyan'), ('continental', 'Continental'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('italian', 'Italian'), ('american', 'American'), ('arabic', 'Arabic/Middle Eastern'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('mixed', 'Mixed/International')], default='local', max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(default='Nairobi', max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate', max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate', max_digits=12, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('delivery_available', models.BooleanField(default=False)),
                ('takeaway_available', models.BooleanField(default=True)),
                ('dine_in_available', models.BooleanField(default=True)),
                ('accepts_card', models.BooleanField(default=False)),
                ('wifi_available', models.BooleanField(default=False)),
                ('main_image', cloudinary.models.CloudinaryField(blank=True, help_text='Main photo of the restaurant', max_length=255, null=True, verbose_name='food_vendor_images')),
                ('image_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='food_vendor_images')),
                ('image_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='food_vendor_images')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Vendor',
                'verbose_name_plural': 'Food Vendors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('snack', 'Snack')], default='main_course', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='menu_item_images')),
                ('is_available', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='food.foodvendor')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='food.foodvendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'user')},
            },
        ),
    ]
