# Generated by Django 4.2 on 2026-01-01 14:19

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favorite Listing',
                'verbose_name_plural': 'Favorite Listings',
            },
        ),
        migrations.CreateModel(
            name='HousingListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('rental', 'Rental'), ('sublet', 'Sublet'), ('roommate', 'Roommate Wanted'), ('housing_wanted', 'Housing Wanted')], default='rental', max_length=20)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('dorm', 'Dorm Room'), ('other', 'Other')], default='apartment', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(default='Nairobi', max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_period', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('semester', 'Per Semester')], default='monthly', max_length=20)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('utilities_included', models.BooleanField(default=False)),
                ('bedrooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('square_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('furnished', models.CharField(choices=[('furnished', 'Fully Furnished'), ('semi', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20)),
                ('available_from', models.DateField()),
                ('lease_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list of amenities', null=True)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_preference', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('both', 'Both')], default='both', max_length=20)),
                ('main_image', cloudinary.models.CloudinaryField(blank=True, help_text='Main photo of the property', max_length=255, null=True, verbose_name='housing_images')),
                ('image_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='housing_images')),
                ('image_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='housing_images')),
                ('image_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='housing_images')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Housing Listing',
                'verbose_name_plural': 'Housing Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.AddField(
            model_name='favoritelisting',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.housinglisting'),
        ),
        migrations.AddField(
            model_name='favoritelisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favoritelisting',
            unique_together={('user', 'listing')},
        ),
    ]
