# Generated by Django 4.2 on 2026-01-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_favoritelisting_housinglisting_delete_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housinglisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate (optional)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='housinglisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate (optional)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='housinglisting',
            name='address',
            field=models.CharField(default='P.O. Box 43844-00100, Nairobi', max_length=200),
        ),
    ]
