# Generated by Django 4.2 on 2026-01-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_housinglisting_latitude_housinglisting_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinglisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate (optional)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='housinglisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate (optional)', max_digits=12, null=True),
        ),
    ]
